import type { Response, Schema, SchemaProperty } from '../models/openapi.model';

export const PROBLEM_SCHEMA: Omit<Schema, 'id'> = {
  name: 'Problem',
  description: 'Modelo de error estándar RFC 7807',
  additionalProperties: null,
  properties: [
    {
      id: '',
      name: 'type',
      type: 'string',
      format: 'uri',
      description: 'URI que identifica el tipo de error',
      example: 'https://api.example.com/problems/validation-error',
      minimum: '',
      maximum: '',
      pattern: '',
      required: false,
      ref: '',
      enumValues: [],
      nullable: false,
      maxLength: '',
    },
    {
      id: '',
      name: 'status',
      type: 'integer',
      format: 'int32',
      description: 'Código HTTP del error',
      example: '400',
      minimum: '0',
      maximum: '999',
      pattern: '',
      required: true,
      ref: '',
      enumValues: [],
      nullable: false,
      maxLength: '',
    },
    {
      id: '',
      name: 'title',
      type: 'string',
      format: '',
      description: 'Título corto del error',
      example: 'Validation Error',
      minimum: '',
      maximum: '',
      pattern: '',
      required: true,
      ref: '',
      enumValues: [],
      nullable: false,
      maxLength: '',
    },
    {
      id: '',
      name: 'detail',
      type: 'string',
      format: '',
      description: 'Descripción detallada del error',
      example: 'One or more fields are invalid.',
      minimum: '',
      maximum: '',
      pattern: '',
      required: true,
      ref: '',
      enumValues: [],
      nullable: false,
      maxLength: '',
    },
    {
      id: '',
      name: 'instance',
      type: 'string',
      format: 'uri',
      description: 'URI de la instancia del error',
      example: 'https://api.example.com/problems/validation-error/12345',
      minimum: '',
      maximum: '',
      pattern: '',
      required: false,
      ref: '',
      enumValues: [],
      nullable: false,
      maxLength: '',
    },
  ] as SchemaProperty[],
};

export interface GenericResponseDef {
  name: string;
  code: string;
  description: string;
  detail: string;
  title: string;
  typeUri: string;
}

export const GENERIC_ERROR_RESPONSES: GenericResponseDef[] = [
  {
    name: 'BadRequest',
    code: '400',
    description: 'Bad Request',
    detail: 'La petición no cumple con el formato esperado.',
    title: 'Bad Request',
    typeUri: 'https://api.example.com/problems/validation-error',
  },
  {
    name: 'Unauthorized',
    code: '401',
    description: 'Unauthorized',
    detail: 'Credenciales inválidas o ausentes.',
    title: 'Unauthorized',
    typeUri: 'https://api.example.com/problems/auth-error',
  },
  {
    name: 'Forbidden',
    code: '403',
    description: 'Forbidden',
    detail: 'No tiene permisos para acceder a este recurso.',
    title: 'Forbidden',
    typeUri: 'https://api.example.com/problems/auth-error',
  },
  {
    name: 'NotFound',
    code: '404',
    description: 'Not Found',
    detail: 'El recurso solicitado no existe.',
    title: 'Not Found',
    typeUri: 'https://api.example.com/problems/not-found',
  },
  {
    name: 'TooManyRequests',
    code: '429',
    description: 'El sistema NO admite mas peticiones.',
    detail: 'El sistema no admite mas peticiones. Intentelo más tarde.',
    title: 'Too Many Requests',
    typeUri: 'https://api.example.com/problems/validation-error',
  },
  {
    name: 'UnexpectedError',
    code: '500',
    description: 'Unexpected Error',
    detail: 'Se ha producido un error inesperado.',
    title: 'Internal Server Error',
    typeUri: 'https://api.example.com/problems/server-error',
  },
  {
    name: 'NotImplemented',
    code: '501',
    description: 'Not Implemented',
    detail: 'La funcionalidad solicitada no está implementada.',
    title: 'Not Implemented',
    typeUri: 'https://api.example.com/problems/not-implemented',
  },
  {
    name: 'ServiceUnavailable',
    code: '503',
    description: 'Service Unavailable',
    detail: 'El servicio no está disponible temporalmente.',
    title: 'Service Unavailable',
    typeUri: 'https://api.example.com/problems/service-unavailable',
  },
];
